import './globals.css'

import { Jost } from 'next/font/google'

import Header from '@/components/Header/Header'

import Footer from '@/components/footer/Footer'
import Promotion from '@/components/promotion/promotion'



const jost = Jost({ 
                subsets: ['latin'],
                display: 'swap',

                })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

 

  return (
    <html lang="en">
      
      <body className={jost.className}>
        <Header/>
        <Promotion />
        <main className='main'>
        {children}
        </main>
        <Footer/>
      </body>
   
    </html>
  )
}
